#include <stdio.h>
#include <stdlib.h>
#include "header/visual.h"

void write_vtkFile(char *szProblem, int timeStepNumber, double xlength, double ylength, int imax, int jmax, double dx, double dy, double **U, double **V, double **P) {
    char szFileName[80];
    FILE *fp = NULL;

    system("mkdir -p vtk");

    sprintf(szFileName, "vtk/%s.%i.vtk", szProblem, timeStepNumber);
    fp = fopen(szFileName, "w");

    write_vtkFileHeader(fp, imax, jmax, dx, dy);
    write_vtkPointCoordinates(fp, imax, jmax, dx, dy);

    // write velocity
    fprintf(fp, "VECTORS velocity float\n");
    for (int j = 0; j <= jmax; j++) {
        for (int i = 0; i <= imax; i++) {
            fprintf(fp, "%f %f 0\n", U[i][j], V[i][j]);
        }
    }

    // write pressure
    fprintf(fp, "SCALARS pressure float 1\n");
    fprintf(fp, "LOOKUP_TABLE default\n");
    for (int j = 0; j <= jmax; j++) {
        for (int i = 0; i <= imax; i++) {
            fprintf(fp, "%f ", P[i][j]);
        }
    }

    fclose(fp);
}

void write_vtkFileHeader(FILE *fp, int imax, int jmax, double dx, double dy) {
    fprintf(fp, "# vtk DataFile Version 3.0\n");
    fprintf(fp, "Generated by CFD simulation\n");
    fprintf(fp, "ASCII\n");
    fprintf(fp, "DATASET STRUCTURED_POINTS\n");
    fprintf(fp, "DIMENSIONS %d %d 1\n", imax + 1, jmax + 1);
    fprintf(fp, "SPACING %f %f 1.0\n", dx, dy);
    fprintf(fp, "ORIGIN 0 0 0\n");
}

void write_vtkPointCoordinates(FILE *fp, int imax, int jmax, double dx, double dy) {
    int i, j;
    int total_points = (imax + 1) * (jmax + 1);
    
    // Write the point data
    fprintf(fp, "POINT_DATA %d\n", total_points);
    
    // Write the scalar data for 'u'
    fprintf(fp, "SCALARS u float 1\n");
    fprintf(fp, "LOOKUP_TABLE default\n");
    for (j = 0; j <= jmax; j++) {
        for (i = 0; i <= imax; i++) {
            // Example calculation for u
            fprintf(fp, "%f ", i * dx);
        }
    }
    fprintf(fp, "\n");
    
    // Write the scalar data for 'v'
    fprintf(fp, "SCALARS v float 1\n");
    fprintf(fp, "LOOKUP_TABLE default\n");
    for (j = 0; j <= jmax; j++) {
        for (i = 0; i <= imax; i++) {
            fprintf(fp, "%f ", j * dy);
        }
    }
    fprintf(fp, "\n");
}
